# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ae8197d4372433b2fdc2552cd8fa132a26a2081c57387254b2d5bdbe7c41345ebf6c253b178fb696298f17c564d179c1248a54272004d77af2f2577b331ea0a

test:
  secret_key_base: 7292abbc08c519fe433330ded3ad82a3ff53bd66450e8ea77675cf69a56a7acfac035992f860f02a12de2104df1f439034bc1e346f0c80aadccb7732b30d26f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
